
guard :minitest, all_on_start: false do
  watch(%r{^lib/(.+)\.rb$})                 { |m| "test/#{m[1]}_test.rb" }
  watch(%r{^lib/.*})                        { "test" }
  watch(%r{^app/assets/.*})                 { "test" }
  watch(%r{^test/.+_test\.rb$})
  watch('test/test_helper.rb')              { "test" }
  watch('test/test_helper_integration.rb')  { "test" }
end

guard 'livereload', apply_css_live: true, override_url: true do
  ignore(%r{cache})
  watch(%r{app/assets/.*\.(css|scss)}) { "assets/style_bitz_style_guide.css" }
  watch(%r{app/(controllers|helpers|views)})
end
